# Generated by Django 5.1.1 on 2024-12-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.IntegerField(max_length=25)),
                ('password', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='registering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('password', models.IntegerField(max_length=30)),
                ('email', models.IntegerField(max_length=20)),
            ],
        ),
    ]
