# Generated by Django 5.1.1 on 2024-12-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irohub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registering',
            name='email',
            field=models.CharField(max_length=20),
        ),
    ]
