# Generated by Django 5.1.3 on 2024-12-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irohub', '0003_remove_contact_email_remove_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='password1',
            new_name='message',
        ),
    ]
