# Generated by Django 5.1.3 on 2025-01-01 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irohub', '0004_rename_password1_contact_message'),
        ('wipro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.IntegerField()),
                ('bookingtime', models.IntegerField()),
                ('userreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irohub.registering')),
                ('userser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wipro.service')),
            ],
        ),
    ]
