# Generated by Django 5.1.3 on 2025-01-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irohub', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingdate',
            field=models.CharField(max_length=20),
        ),
    ]
