# Generated by Django 5.1.3 on 2025-01-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irohub', '0006_alter_booking_bookingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingtime',
            field=models.CharField(max_length=20),
        ),
    ]
