# Generated by Django 5.1.3 on 2025-01-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irohub', '0007_alter_booking_bookingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
