# Generated by Django 5.1.3 on 2024-12-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='null.jpg', upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='saloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=20)),
                ('image1', models.ImageField(default='null.jpg', upload_to='image1')),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=20)),
                ('image2', models.ImageField(default='null.jpg', upload_to='image2')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('saloon', models.CharField(max_length=50)),
            ],
        ),
    ]
